# Import modules directly
import app.services.simulation_service as simulation_service
import app.services.prediction_service as prediction_service
import app.services.routing_service as routing_service
import app.services.nudge_service as nudge_service
import app.services.agent_service as agent_service
import app.services.kpi_service as kpi_service
from app.services.scenario_service import scenario_service
import app.services.edge_ingest as edge_ingest
import app.services.stream_processing as stream_processing
